version: "3.8"
services:
  # postgres:
  #   container_name: ${DB_NAME:-db}
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - postgres_data:/var/lib/posgresql/data
  #   restart: unless-stopped
  #   networks:
  #     - postgres

  nest:
    container_name: nest
    image: node:latest
    # depends_on:
      # - postgres
    ports:
      - "${nest_PORT:-5500}:${nest_PORT:-5500}"
      - "5555:5555"
    restart: always
    command: /bin/sh -c "npm i bun && tail -f /dev/null"
    volumes:
      - "./nest:/app"
    working_dir: /app
    networks:
      - postgres

  # file_service:
  #   container_name: file_service
  #   image: node:latest
  #   ports:
  #     - "${FILESERVICE_PORT:-5170}:${FILESERVICE_PORT:-5170}"
  #   restart: always
  #   command: /bin/sh -c "npm install && npm run start:dev"
  #   environment:
  #     API: ${API}
  #     nest_HOST: ${nest_HOST}
  #     FILESERVICE_PORT: ${FILESERVICE_PORT}
  #     CORS: ${CORS}
  #   volumes:
  #     - "./file_service:/app"
  #   working_dir: /app
  #   networks:
  #     - postgres

  # front:
  #   container_name: front
  #   image: node:latest
  #   volumes:
  #     - ./front/:/app
  #   working_dir: /app
  #   command: sh -c "npm install && npm run dev"
  #   ports:
  #     - "${FRONT_PORT:-5000}:${FRONT_PORT:-5000}"

volumes:
  postgres_data:
    driver: local

networks:
  postgres:
    driver: bridge
